#!/usr/bin/env python3
"""Bundle the simulator and every module it touches into one Luau chunk.

The standalone `luau` CLI sandboxes each required file with a fresh, read-only
global table, so a stubbed `game`/`Instance` set in one file is invisible to the
next. Concatenating everything into a single chunk keeps one shared global
environment, which is all the simulator needs.

    python3 tests/bundle.py && luau tests/.bundle.luau
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "tests" / ".bundle.luau"

modules = {"./RobloxStub": ROOT / "tests" / "RobloxStub.luau"}
for folder, prefix in (("shared", "../src/shared/"), ("server", "../src/server/")):
    for path in sorted((ROOT / "src" / folder).glob("*.luau")):
        if path.name.endswith(".server.luau") or path.name.endswith(".client.luau"):
            continue
        modules[prefix + path.stem] = path

parts = [
    "--!nocheck",
    "-- GENERATED by tests/bundle.py -- do not edit.",
    "local __loaders = {}",
    "local __cache = {}",
]

for key, path in modules.items():
    parts.append(f'__loaders[{key!r}] = function()')
    parts.append(path.read_text())
    parts.append("end")

parts.append(
    """
local function __load(name)
	if __cache[name] == nil then
		local loader = __loaders[name]
		if not loader then
			error("bundle: no module named " .. tostring(name))
		end
		__cache[name] = loader()
	end
	return __cache[name]
end
_BUNDLE_LOAD = __load
"""
)

parts.append((ROOT / "tests" / "simulate.luau").read_text())

OUT.write_text("\n".join(parts))
print(f"wrote {OUT.relative_to(ROOT)} ({len(modules)} modules)")
